export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
export default function RootLayout({ children }) {
    console.log("montando layout")
    return (
        <html lang="en">
            <body>
                <header>
                    <div>Menu principal</div> {/* O menu foi movido para o layout */}
                </header>
                <main>{children}</main>
                <footer>
                    <p>Global Footer</p>
                </footer>
            </body>
        </html>
    );
  }